sudo: required

services:
  - docker

install: true

before_script:
  - export MYSQL_ROOT_PASSWORD=duubidoo
  - export SECRET_KEY_BASE="we-dont-need-a-secret-here"
  - export DB_USER=root
  - export DB_PASSWORD=duubidoo
  - docker-compose pull
  - docker-compose build

script:
  - docker-compose run --rm app bash -c "./docker/wait-for-services.sh && bundle exec rake db:setup spec RAILS_ENV=test"
