sudo: required

services:
  - docker

install: true # skip the installation step entirely

before_script:
  - sudo sysctl -w vm.max_map_count=262144 # Required for Elasticsearch 5
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
  - docker-compose pull
  - docker-compose -f docker-compose.test.yml build
  - docker-compose -f docker-compose.test.yml run --rm test bash -c "./docker/wait-for-services.sh && bundle exec rake db:create spec rubocop"

  - docker-compose build
  - docker tag dockerrails_app $DOCKER_USERNAME/docker-rails
  - docker push $DOCKER_USERNAME/docker-rails
