version: '2'
services:
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD
    volumes:
      - "db-data:/var/lib/mysql"

  backup:
    image: schickling/mysql-backup-s3
    links:
      - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD
      - MYSQLDUMP_DATABASE
      - S3_ACCESS_KEY_ID
      - S3_SECRET_ACCESS_KEY
      - S3_BUCKET
      - S3_REGION
      - S3_PREFIX=backup
      - SCHEDULE

  elasticsearch:
    image: elasticsearch:2
    volumes:
      - "es-data:/usr/share/elasticsearch/data"

  memcached:
    image: memcached:1.4-alpine

  redis:
    image: redis:3.2-alpine

  app: &app_base
    build: .
    environment:
      - MYSQL_HOST=db
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - REDIS_URL=redis://redis:6379/0
      - MEMCACHED_HOST=memcached
      - SECRET_KEY_BASE
      - DB_USER
      - DB_PASSWORD
      - RAILS_ENV
      - PASSENGER_APP_ENV
    ports:
      - "80"
    links:
      - elasticsearch
      - db
      - redis
      - memcached
    volumes:
      - .:/home/app/webapp

  worker:
    <<: *app_base
    command: bundle exec sidekiq
    ports: []
    depends_on:
      - app

volumes:
  db-data:
  es-data:
