local:
  url: redis://localhost:6379/1

test:
  url: <%= ENV['REDIS_CABLE_URL'] %>
  channel_prefix: docker_rails_test

production:
  url: <%= ENV['REDIS_CABLE_URL'] %>
  channel_prefix: docker_rails_production
